

ORDER_FIELDS = [
    'number',
    'name',
    'created-at',
    'total-discounts',
    'token',
    'updated-at',
    'total-price',
    'landing-site',
    'taxes-included',
    'id',
    'referring-site',
    'total-line-items-price',
    'subtotal-price',
    'note',
    'gateway',
    'fulfillment-status',
    'financial-status',
    'currency',
    'closed-at',
    'buyer-accepts-marketing',
    'total-tax',
    'total-weight',
    'email',
    'browser-ip',
    'landing-site-ref',
    'order-number',
    'customer',
    'tax-lines',
    'shipping-address',
    'shipping-lines',
    'billing-address',
    'line-items',
    'note-attributes',
]

[(u'"%s": "%s"' % (field.tag, field.tag.replace('-', '_'))) for field in list(order)]

ORDER_FIELD_MATCH = {
    'number': 'number',
    'name': 'name',
    'created-at': 'created_at',
    'total-discounts': 'total_discounts',
    'token': 'token',
    'updated-at': 'updated_at',
    'total-price': 'total_price',
    'landing-site': 'landing_site',
    'taxes-included': 'taxes_included',
    'id': 'id',
    'referring-site': 'referring_site',
    'total-line-items-price': 'total_line_items_price',
    'subtotal-price': 'subtotal_price',
    'note': 'note',
    'gateway': 'gateway',
    'fulfillment-status': 'fulfillment_status',
    'financial-status': 'financial_status',
    'currency': 'currency',
    'closed-at': 'closed_at',
    'buyer-accepts-marketing': 'buyer_accepts_marketing',
    'total-tax': 'total_tax',
    'total-weight': 'total_weight',
    'email': 'email',
    'browser-ip': 'browser_ip',
    'landing-site-ref': 'landing_site_ref',
    'order-number': 'order_number',
    'customer': 'customer',
    'tax-lines': 'tax_lines',
    'shipping-address': 'shipping_address',
    'shipping-lines': 'shipping_lines',
    'billing-address': 'billing_address',
    'line-items': 'line_items',
    'note-attributes': 'note_attributes',
}

{'billing_address': {'field_name': 'billing-address', 'type': None}, 'browser_ip': {'field_name': 'browser-ip', 'type': 'yaml'}, 'buyer_accepts_marketing': {'field_name': 'buyer-accepts-marketing', 'type': 'boolean'}, 'closed_at': {'field_name': 'closed-at', 'type': 'datetime'}, 'created_at': {'field_name': 'created-at', 'type': 'datetime'}, 'currency': {'field_name': 'currency', 'type': None}, 'customer': {'field_name': 'customer', 'type': None}, 'email': {'field_name': 'email', 'type': None}, 'financial_status': {'field_name': 'financial-status', 'type': None}, 'fulfillment_status': {'field_name': 'fulfillment-status', 'type': None}, 'gateway': {'field_name': 'gateway', 'type': None}, 'id': {'field_name': 'id', 'type': 'integer'}, 'landing_site': {'field_name': 'landing-site', 'type': None}, 'landing_site_ref': {'field_name': 'landing-site-ref', 'type': 'yaml'}, 'line_items': {'field_name': 'line-items', 'type': 'array'}, 'name': {'field_name': 'name', 'type': None}, 'note': {'field_name': 'note', 'type': None}, 'note_attributes': {'field_name': 'note-attributes', 'type': 'array'}, 'number': {'field_name': 'number', 'type': 'integer'}, 'order_number': {'field_name': 'order-number', 'type': 'integer'}, 'referring_site': {'field_name': 'referring-site', 'type': None}, 'shipping_address': {'field_name': 'shipping-address', 'type': None}, 'shipping_lines': {'field_name': 'shipping-lines', 'type': 'array'}, 'subtotal_price': {'field_name': 'subtotal-price', 'type': 'decimal'}, 'tax_lines': {'field_name': 'tax-lines', 'type': 'array'}, 'taxes_included': {'field_name': 'taxes-included', 'type': 'boolean'}, 'token': {'field_name': 'token', 'type': None}, 'total_discounts': {'field_name': 'total-discounts', 'type': 'decimal'}, 'total_line_items_price': {'field_name': 'total-line-items-price', 'type': 'decimal'}, 'total_price': {'field_name': 'total-price', 'type': 'decimal'}, 'total_tax': {'field_name': 'total-tax', 'type': 'decimal'}, 'total_weight': {'field_name': 'total-weight', 'type': 'integer'}, 'updated_at': {'field_name': 'updated-at', 'type': 'datetime'}}
